"""ET Rules seeder for the Rules shard.

Pre-populates the rules table with Employment Tribunal Rules of Procedure 2013
(SI 2013/1237 as amended) and key Practice Directions.
"""

import json
import logging
import uuid

logger = logging.getLogger(__name__)


class RuleSeeder:
    """Seed the rules table with hard-coded ET procedural rules."""

    # ------------------------------------------------------------------
    # ET Rules of Procedure 2013 (selected key rules)
    # ------------------------------------------------------------------

    ET_RULES: list[dict] = [
        {
            "rule_number": "Rule 1",
            "title": "Overriding Objective",
            "description": "Deal with cases fairly and justly, including avoiding unnecessary formality, delay and expense.",
            "category": "case_management",
            "trigger_type": "custom",
            "deadline_days": None,
            "deadline_type": "calendar_days",
            "applies_to": "tribunal",
            "is_mandatory": True,
            "consequence_of_breach": "Tribunal must have regard to overriding objective in exercising powers",
            "strike_out_risk": False,
            "unless_order_applicable": False,
            "jurisdiction": "England & Wales",
            "statute": "Employment Tribunals Rules of Procedure 2013",
            "section": "1",
        },
        {
            "rule_number": "Rule 2",
            "title": "Overriding Objective - Parties' Obligation",
            "description": "Parties and representatives shall assist the Tribunal in furthering the overriding objective.",
            "category": "case_management",
            "trigger_type": "custom",
            "deadline_days": None,
            "deadline_type": "calendar_days",
            "applies_to": "both",
            "is_mandatory": True,
            "consequence_of_breach": "Costs implications; failure to cooperate may be considered in case management",
            "strike_out_risk": False,
            "unless_order_applicable": False,
            "jurisdiction": "England & Wales",
            "statute": "Employment Tribunals Rules of Procedure 2013",
            "section": "2",
        },
        {
            "rule_number": "Rule 4",
            "title": "Time Limits and Extensions",
            "description": "Time limits for compliance with orders; Tribunal power to extend or shorten time.",
            "category": "case_management",
            "trigger_type": "date_of_order",
            "deadline_days": 28,
            "deadline_type": "calendar_days",
            "applies_to": "both",
            "is_mandatory": True,
            "consequence_of_breach": "Default action; unless order may follow",
            "strike_out_risk": True,
            "unless_order_applicable": True,
            "jurisdiction": "England & Wales",
            "statute": "Employment Tribunals Rules of Procedure 2013",
            "section": "4",
        },
        {
            "rule_number": "Rule 10",
            "title": "Case Management Orders - General Powers",
            "description": "Tribunal may at any stage make a case management order, including varying or revoking earlier orders.",
            "category": "case_management",
            "trigger_type": "date_of_order",
            "deadline_days": None,
            "deadline_type": "calendar_days",
            "applies_to": "tribunal",
            "is_mandatory": False,
            "consequence_of_breach": "Non-compliance may lead to unless orders or strike-out",
            "strike_out_risk": True,
            "unless_order_applicable": True,
            "jurisdiction": "England & Wales",
            "statute": "Employment Tribunals Rules of Procedure 2013",
            "section": "10",
        },
        {
            "rule_number": "Rule 13",
            "title": "Unless Orders",
            "description": "An order may specify that unless it is complied with by the date specified, the claim or response shall be dismissed without further order.",
            "category": "unless_order",
            "trigger_type": "date_of_order",
            "deadline_days": 14,
            "deadline_type": "calendar_days",
            "applies_to": "both",
            "is_mandatory": True,
            "consequence_of_breach": "Automatic strike-out of claim or response",
            "strike_out_risk": True,
            "unless_order_applicable": True,
            "jurisdiction": "England & Wales",
            "statute": "Employment Tribunals Rules of Procedure 2013",
            "section": "13",
        },
        {
            "rule_number": "Rule 16",
            "title": "Response to Claim - Time Limit",
            "description": "The response (ET3) must be presented within 28 days of the date the copy of the claim was sent.",
            "category": "initial_consideration",
            "trigger_type": "date_of_claim",
            "deadline_days": 28,
            "deadline_type": "calendar_days",
            "applies_to": "respondent",
            "is_mandatory": True,
            "consequence_of_breach": "Default judgment may be entered; respondent barred from participating",
            "strike_out_risk": True,
            "unless_order_applicable": False,
            "jurisdiction": "England & Wales",
            "statute": "Employment Tribunals Rules of Procedure 2013",
            "section": "16",
        },
        {
            "rule_number": "Rule 17",
            "title": "Extension of Time for Response",
            "description": "Application to extend time for presenting response; must be made before expiry of original time limit.",
            "category": "initial_consideration",
            "trigger_type": "date_of_claim",
            "deadline_days": 28,
            "deadline_type": "calendar_days",
            "applies_to": "respondent",
            "is_mandatory": False,
            "consequence_of_breach": "Extension refused; default judgment proceeds",
            "strike_out_risk": True,
            "unless_order_applicable": False,
            "jurisdiction": "England & Wales",
            "statute": "Employment Tribunals Rules of Procedure 2013",
            "section": "17",
        },
        {
            "rule_number": "Rule 21",
            "title": "Default Judgments",
            "description": "If no response received or accepted, Tribunal may issue default judgment on liability.",
            "category": "default_judgment",
            "trigger_type": "date_of_response",
            "deadline_days": None,
            "deadline_type": "calendar_days",
            "applies_to": "tribunal",
            "is_mandatory": False,
            "consequence_of_breach": "Judgment entered against respondent",
            "strike_out_risk": False,
            "unless_order_applicable": False,
            "jurisdiction": "England & Wales",
            "statute": "Employment Tribunals Rules of Procedure 2013",
            "section": "21",
        },
        {
            "rule_number": "Rule 27",
            "title": "Disclosure and Inspection of Documents",
            "description": "Tribunal may order disclosure and inspection of documents relevant to the issues.",
            "category": "disclosure",
            "trigger_type": "date_of_order",
            "deadline_days": 14,
            "deadline_type": "calendar_days",
            "applies_to": "both",
            "is_mandatory": True,
            "consequence_of_breach": "Adverse inference; unless order; costs",
            "strike_out_risk": True,
            "unless_order_applicable": True,
            "jurisdiction": "England & Wales",
            "statute": "Employment Tribunals Rules of Procedure 2013",
            "section": "27",
        },
        {
            "rule_number": "Rule 29",
            "title": "Case Management Orders",
            "description": "Tribunal may at any stage make a case management order on its own initiative or on application.",
            "category": "case_management",
            "trigger_type": "date_of_order",
            "deadline_days": None,
            "deadline_type": "calendar_days",
            "applies_to": "tribunal",
            "is_mandatory": False,
            "consequence_of_breach": "Non-compliance may lead to further orders or unless orders",
            "strike_out_risk": True,
            "unless_order_applicable": True,
            "jurisdiction": "England & Wales",
            "statute": "Employment Tribunals Rules of Procedure 2013",
            "section": "29",
        },
        {
            "rule_number": "Rule 37",
            "title": "Strike Out",
            "description": "Tribunal may strike out a claim or response on specified grounds including scandalous, vexatious, or no reasonable prospect of success.",
            "category": "strike_out",
            "trigger_type": "custom",
            "deadline_days": None,
            "deadline_type": "calendar_days",
            "applies_to": "both",
            "is_mandatory": False,
            "consequence_of_breach": "Claim or response struck out",
            "strike_out_risk": True,
            "unless_order_applicable": False,
            "jurisdiction": "England & Wales",
            "statute": "Employment Tribunals Rules of Procedure 2013",
            "section": "37",
        },
        {
            "rule_number": "Rule 38",
            "title": "Deposit Orders",
            "description": "Tribunal may order a deposit as a condition of continuing to advance an allegation or argument.",
            "category": "deposit_order",
            "trigger_type": "date_of_order",
            "deadline_days": 21,
            "deadline_type": "calendar_days",
            "applies_to": "both",
            "is_mandatory": True,
            "consequence_of_breach": "Allegation or argument treated as withdrawn; costs warning",
            "strike_out_risk": True,
            "unless_order_applicable": False,
            "jurisdiction": "England & Wales",
            "statute": "Employment Tribunals Rules of Procedure 2013",
            "section": "38",
        },
        {
            "rule_number": "Rule 39",
            "title": "Deposit Orders - Consequences",
            "description": "If deposit not paid, the allegation is treated as withdrawn. If party loses, deposit may be paid to other side.",
            "category": "deposit_order",
            "trigger_type": "date_of_order",
            "deadline_days": 21,
            "deadline_type": "calendar_days",
            "applies_to": "both",
            "is_mandatory": True,
            "consequence_of_breach": "Allegation withdrawn; costs risk",
            "strike_out_risk": True,
            "unless_order_applicable": False,
            "jurisdiction": "England & Wales",
            "statute": "Employment Tribunals Rules of Procedure 2013",
            "section": "39",
        },
        {
            "rule_number": "Rule 41",
            "title": "Preparation Time Orders",
            "description": "Tribunal may make a preparation time order requiring a party to pay the other party's preparation time costs.",
            "category": "costs",
            "trigger_type": "date_of_judgment",
            "deadline_days": None,
            "deadline_type": "calendar_days",
            "applies_to": "both",
            "is_mandatory": False,
            "consequence_of_breach": "Enforcement proceedings",
            "strike_out_risk": False,
            "unless_order_applicable": False,
            "jurisdiction": "England & Wales",
            "statute": "Employment Tribunals Rules of Procedure 2013",
            "section": "41",
        },
        {
            "rule_number": "Rule 53",
            "title": "Reconsideration of Judgments",
            "description": "A party may apply for reconsideration of a judgment within 14 days of the date the judgment was sent.",
            "category": "judgment",
            "trigger_type": "date_of_judgment",
            "deadline_days": 14,
            "deadline_type": "calendar_days",
            "applies_to": "both",
            "is_mandatory": True,
            "consequence_of_breach": "Application refused as out of time",
            "strike_out_risk": False,
            "unless_order_applicable": False,
            "jurisdiction": "England & Wales",
            "statute": "Employment Tribunals Rules of Procedure 2013",
            "section": "53",
        },
        {
            "rule_number": "Rule 62",
            "title": "Reasons for Judgments",
            "description": "Written reasons shall be given for any judgment; may be requested within 14 days.",
            "category": "judgment",
            "trigger_type": "date_of_judgment",
            "deadline_days": 14,
            "deadline_type": "calendar_days",
            "applies_to": "both",
            "is_mandatory": True,
            "consequence_of_breach": "Right to written reasons lost if not requested in time",
            "strike_out_risk": False,
            "unless_order_applicable": False,
            "jurisdiction": "England & Wales",
            "statute": "Employment Tribunals Rules of Procedure 2013",
            "section": "62",
        },
        {
            "rule_number": "Rule 76",
            "title": "Costs Orders - When Made",
            "description": "Tribunal may make a costs order where party or representative has acted vexatiously, abusively, disruptively or otherwise unreasonably.",
            "category": "costs",
            "trigger_type": "custom",
            "deadline_days": None,
            "deadline_type": "calendar_days",
            "applies_to": "both",
            "is_mandatory": False,
            "consequence_of_breach": "Costs awarded against party; up to 20,000 GBP without detailed assessment",
            "strike_out_risk": False,
            "unless_order_applicable": False,
            "jurisdiction": "England & Wales",
            "statute": "Employment Tribunals Rules of Procedure 2013",
            "section": "76",
        },
        # Practice Directions
        {
            "rule_number": "PD - Witness Statements",
            "title": "Exchange of Witness Statements",
            "description": "Witness statements to be exchanged by date set in case management order, typically 28 days before hearing.",
            "category": "witnesses",
            "trigger_type": "date_of_hearing",
            "deadline_days": 28,
            "deadline_type": "calendar_days",
            "applies_to": "both",
            "is_mandatory": True,
            "consequence_of_breach": "Witness may not be permitted to give evidence; unless order",
            "strike_out_risk": True,
            "unless_order_applicable": True,
            "jurisdiction": "England & Wales",
            "statute": "Practice Direction",
            "section": "PD",
        },
        {
            "rule_number": "PD - Skeleton Arguments",
            "title": "Skeleton Arguments",
            "description": "Skeleton arguments/written submissions to be filed and served before hearing as directed.",
            "category": "hearing",
            "trigger_type": "date_of_hearing",
            "deadline_days": 7,
            "deadline_type": "working_days",
            "applies_to": "both",
            "is_mandatory": False,
            "consequence_of_breach": "May not be considered; costs implications",
            "strike_out_risk": False,
            "unless_order_applicable": False,
            "jurisdiction": "England & Wales",
            "statute": "Practice Direction",
            "section": "PD",
        },
        {
            "rule_number": "PD - Hearing Bundle",
            "title": "Agreed Hearing Bundle",
            "description": "Parties to prepare and agree an indexed hearing bundle to be filed in advance of hearing.",
            "category": "hearing",
            "trigger_type": "date_of_hearing",
            "deadline_days": 14,
            "deadline_type": "calendar_days",
            "applies_to": "both",
            "is_mandatory": True,
            "consequence_of_breach": "Adjournment; wasted costs order; unless order for bundle preparation",
            "strike_out_risk": True,
            "unless_order_applicable": True,
            "jurisdiction": "England & Wales",
            "statute": "Practice Direction",
            "section": "PD",
        },
    ]

    async def seed(self, db) -> int:
        """Insert or update rules from ET_RULES list.

        Uses INSERT ... ON CONFLICT (upsert) on rule_number to be idempotent.
        Returns count of rules inserted/updated.
        """
        if not db:
            raise RuntimeError("Database not available")

        count = 0
        for rule_data in self.ET_RULES:
            rule_id = str(uuid.uuid4())
            tags = json.dumps(rule_data.get("tags", []))

            await db.execute(
                """
                INSERT INTO arkham_rules.rules
                (id, rule_number, title, description, category, trigger_type,
                 deadline_days, deadline_type, applies_to, is_mandatory,
                 consequence_of_breach, strike_out_risk, unless_order_applicable,
                 jurisdiction, statute, section, notes, tags, statutory_source)
                VALUES (:id, :rule_number, :title, :description, :category, :trigger_type,
                        :deadline_days, :deadline_type, :applies_to, :is_mandatory,
                        :consequence_of_breach, :strike_out_risk, :unless_order_applicable,
                        :jurisdiction, :statute, :section, :notes, :tags, :statutory_source)
                ON CONFLICT (rule_number) DO UPDATE SET
                    title = EXCLUDED.title,
                    description = EXCLUDED.description,
                    category = EXCLUDED.category,
                    trigger_type = EXCLUDED.trigger_type,
                    deadline_days = EXCLUDED.deadline_days,
                    deadline_type = EXCLUDED.deadline_type,
                    applies_to = EXCLUDED.applies_to,
                    is_mandatory = EXCLUDED.is_mandatory,
                    consequence_of_breach = EXCLUDED.consequence_of_breach,
                    strike_out_risk = EXCLUDED.strike_out_risk,
                    unless_order_applicable = EXCLUDED.unless_order_applicable,
                    jurisdiction = EXCLUDED.jurisdiction,
                    statute = EXCLUDED.statute,
                    section = EXCLUDED.section,
                    updated_at = CURRENT_TIMESTAMP
                """,
                {
                    "id": rule_id,
                    "rule_number": rule_data["rule_number"],
                    "title": rule_data["title"],
                    "description": rule_data["description"],
                    "category": rule_data["category"],
                    "trigger_type": rule_data["trigger_type"],
                    "deadline_days": rule_data.get("deadline_days"),
                    "deadline_type": rule_data.get("deadline_type", "calendar_days"),
                    "applies_to": rule_data.get("applies_to", "both"),
                    "is_mandatory": rule_data.get("is_mandatory", True),
                    "consequence_of_breach": rule_data.get("consequence_of_breach", ""),
                    "strike_out_risk": rule_data.get("strike_out_risk", False),
                    "unless_order_applicable": rule_data.get("unless_order_applicable", False),
                    "jurisdiction": rule_data.get("jurisdiction", "England & Wales"),
                    "statute": rule_data.get("statute", "Employment Tribunals Rules of Procedure 2013"),
                    "section": rule_data.get("section", ""),
                    "notes": rule_data.get("notes", ""),
                    "tags": tags,
                    "statutory_source": "ET Rules of Procedure 2013 (SI 2013/1237)",
                },
            )
            count += 1

        logger.info(f"Seeded {count} ET rules")
        return count
