"""Export command -- Phase 5 workflow."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

import click
from rich.console import Console

from ..client import APIError

console = Console()

SHARD_SECTIONS = [
    ("Timeline Events", "timeline_events"),
    ("Disclosure Gaps", "disclosure_gaps"),
    ("Comms Gaps", "comms_gaps"),
    ("Comparator s.13", "comparator_s13"),
    ("Comparator s.26", "comparator_s26"),
]


def _fetch_section(client: object, case_id: str, method_name: str) -> tuple[bool, dict | str]:
    """Attempt to fetch a section. Returns (ok, result_or_error)."""
    method = getattr(client, method_name, None)
    if method is None:
        return False, f"Method {method_name} not found on client"
    try:
        result = method(case_id)
        return True, result
    except APIError as exc:
        return False, f"HTTP {exc.status_code}"
    except Exception as exc:
        return False, str(exc)[:100]


def _format_section(title: str, ok: bool, data: dict | str) -> str:
    """Format a section for the markdown report."""
    lines = [f"## {title}", ""]

    if not ok:
        lines.append(f"**Error:** {data}")
        lines.append("")
        return "\n".join(lines)

    if isinstance(data, dict):
        # Try to extract a list of items
        for key in ("events", "items", "gaps", "elements", "profiles"):
            if key in data and isinstance(data[key], list):
                items = data[key]
                lines.append(f"**{len(items)} item(s)**")
                lines.append("")
                for item in items[:50]:  # cap at 50 for readability
                    if isinstance(item, dict):
                        summary_parts = []
                        for field in ("date", "title", "description", "name", "type", "status"):
                            if field in item:
                                summary_parts.append(f"{field}: {item[field]}")
                        lines.append(f"- {' | '.join(summary_parts) if summary_parts else str(item)}")
                    else:
                        lines.append(f"- {item}")
                if len(items) > 50:
                    lines.append(f"- ... and {len(items) - 50} more")
                lines.append("")
                return "\n".join(lines)

        # Fallback: dump key-value pairs
        for k, v in data.items():
            lines.append(f"- **{k}**: {v}")
        lines.append("")
    else:
        lines.append(str(data))
        lines.append("")

    return "\n".join(lines)


@click.command()
@click.option("--case-id", required=True, help="Case UUID for export")
@click.option(
    "--output",
    required=True,
    type=click.Path(path_type=Path),
    help="Output markdown file path",
)
@click.pass_context
def export(ctx: click.Context, case_id: str, output: Path) -> None:
    """Export aggregated shard outputs as a gap report (Phase 5)."""
    client = ctx.obj["client"]

    console.print(f"[bold]Exporting gap report for case [cyan]{case_id}[/][/]\n")

    now = datetime.now(tz=timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    report_lines = [
        "# SHATTERED Gap Report",
        "",
        f"**Case ID:** {case_id}",
        f"**Generated:** {now}",
        f"**Sections:** {len(SHARD_SECTIONS)}",
        "",
        "---",
        "",
    ]

    fetched = 0
    failed = 0

    for title, method_name in SHARD_SECTIONS:
        console.print(f"  Fetching {title}...", end="")
        ok, data = _fetch_section(client, case_id, method_name)

        if ok:
            console.print(f"\r  [green]OK[/]   {title}")
            fetched += 1
        else:
            console.print(f"\r  [red]FAIL[/] {title}: {data}")
            failed += 1

        report_lines.append(_format_section(title, ok, data))

    # Summary section
    report_lines.extend(
        [
            "---",
            "",
            "## Summary",
            "",
            f"- **Sections fetched:** {fetched}",
            f"- **Sections failed:** {failed}",
            f"- **Total sections:** {len(SHARD_SECTIONS)}",
            "",
            "*This report was generated by the SHATTERED CLI export command.*",
            "*Full gap analysis with cross-referencing will be implemented in a future iteration.*",
            "",
        ]
    )

    report_content = "\n".join(report_lines)

    # Write file
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(report_content, encoding="utf-8")

    console.print()
    console.print(f"[bold green]Report written to {output}[/]")
    console.print(f"[dim]{fetched} sections fetched, {failed} failed[/]")
